apis:
  google:
    base_url: "https://maps.googleapis.com"
    place:
      text_search: "/maps/api/place/textsearch/json"
      details: "/maps/api/place/details/json"
      photo: "/maps/api/place/photo"

meta:
  name: 'dirt-awesome'
  title: 'dirt-awesome'
  description: '全国のモトクロスコースの情報共有サイトです。'
  keywords: 'モトクロス,モトクロスコース,Motocross,オフロードコース,練習予定'
  og:
    type: 'article'
